name: Deploy to Azure App Service

on:
    push:
      branches:
        - tootle 

jobs:
    build:
        runs-on: ubuntu-latest
          
        steps:
        - name: Checkout code
          uses: actions/checkout@v2